### ISSUE TITLE
Install into Linux machine

### ISSUE THREAD

**Issue by mtshare** [appknox/isign#10]
How can I install your fork into a Linux machine?
I tried cloning repo and then sudo ./INSTALL.sh but I got:
```
Traceback (most recent call last):
  File "/usr/local/bin/isign", line 4, in <module>
    __import__('pkg_resources').run_script('ak-isign==0.10.7', 'isign')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ak_isign-0.10.7-py2.7.egg/EGG-INFO/scripts/isign", line 4, in <module>
    from isign import isign
  File "/usr/local/lib/python2.7/dist-packages/ak_isign-0.10.7-py2.7.egg/isign/isign.py", line 7, in <module>
    from . import archive
  File "/usr/local/lib/python2.7/dist-packages/ak_isign-0.10.7-py2.7.egg/isign/archive.py", line 85
    class Archive(object, metaclass=abc.ABCMeta):
```

**Comment by mtshare** [comment]
Any solutions?

**Comment by cosmosgenius** [comment]
@mtshare our versions of isign is deployed to pypi as `ak-isign`. You can do `pip install ak-isign` to install our version in any system. Hope it helps :)

**Comment by mtshare** [comment]
@cosmosgenius The installation works but now I got

```
root@Severus:~# isign -h
Traceback (most recent call last):
  File "/usr/local/bin/isign", line 4, in <module>
    from isign import isign
  File "/usr/local/lib/python2.7/dist-packages/isign/isign.py", line 7, in <module>
    from . import archive
  File "/usr/local/lib/python2.7/dist-packages/isign/archive.py", line 85
    class Archive(object, metaclass=abc.ABCMeta):
```

**Comment by subho007** [comment]
@mtshare you need to install it for Python3.

`pip3 install ak-isign`

**Comment by mtshare** [comment]
Thanks, the installation works but now it gives me:

```
isign -o resigned.ipa ./reeder.ipa

Traceback (most recent call last):
  File "/usr/local/bin/isign", line 251, in <module>
    isign.resign(app_path, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/isign/isign.py", line 83, in resign
    alternate_entitlements_path)
  File "/usr/local/lib/python3.5/dist-packages/isign/archive.py", line 405, in resign
    ua = archive.unarchive_to_temp()
  File "/usr/local/lib/python3.5/dist-packages/isign/archive.py", line 253, in unarchive_to_temp
    self.extract_to(self.path, containing_dir)
  File "/usr/local/lib/python3.5/dist-packages/isign/archive.py", line 264, in extract_to
    if fileinfo.is_dir():
AttributeError: 'ZipInfo' object has no attribute 'is_dir'
```

**Comment by cosmosgenius** [comment]
@mtshare would it be possible for you to try it with  python3.6+? Better would be to install isign in an python3.6+ virtualenv rather than system wide.
