### ISSUE TITLE
MacOS re-sign error

### ISSUE THREAD

**Issue by ghost** [appknox/isign#11]
Hi, On Mac OS 10.11.6
```
Traceback (most recent call last):
  File "/usr/local/bin/isign", line 4, in <module>
    __import__('pkg_resources').run_script('ak-isign==0.10.7', 'isign')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1531, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/ak_isign-0.10.7-py2.7.egg/EGG-INFO/scripts/isign", line 4, in <module>
    from isign import isign
  File "/usr/local/lib/python2.7/site-packages/ak_isign-0.10.7-py2.7.egg/isign/isign.py", line 7, in <module>
    from . import archive
  File "/usr/local/lib/python2.7/site-packages/ak_isign-0.10.7-py2.7.egg/isign/archive.py", line 85
    class Archive(object, metaclass=abc.ABCMeta):
                                   ^
SyntaxError: invalid syntax
```
Have you any guess ? I'm not au Python dev.

Regards, Yoann

**Comment by ghost** [comment]
Should I need Python 3 ?

**Comment by subho007** [comment]
yes this is python3 version of isign
