### ISSUE TITLE
AttributeError: 'ZipInfo' object has no attribute 'is_dir'

### ISSUE THREAD

**Issue by shaahin** [appknox/isign#18]
Seems strange but I get this error on my ubuntu 16.04 system with Python 3.5

any ideas?
`Traceback (most recent call last):
  File "/usr/local/bin/isign", line 251, in <module>
    isign.resign(app_path, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/isign/isign.py", line 83, in resign
    alternate_entitlements_path)
  File "/usr/local/lib/python3.5/dist-packages/isign/archive.py", line 405, in resign
    ua = archive.unarchive_to_temp()
  File "/usr/local/lib/python3.5/dist-packages/isign/archive.py", line 253, in unarchive_to_temp
    self.extract_to(self.path, containing_dir)
  File "/usr/local/lib/python3.5/dist-packages/isign/archive.py", line 264, in extract_to
    if fileinfo.is_dir():
AttributeError: 'ZipInfo' object has no attribute 'is_dir'`

**Comment by Raafas** [comment]
`is_dir` is available in Python 3.6+

```sh
sudo add-apt-repository ppa:jonathonf/python-3.6
sudo apt-get update
sudo apt-get install python3.6 libpython3.6
```
Set Python 3.6 as default
`sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2`

Reinstall Pip and set as default for Python3

```sh
curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
python3.6 -m pip -V```
